### ISSUE TITLE
Block Code Node not present

### ISSUE THREAD

**Issue by KingofNothing07** [endlessm/godot-block-coding#121]
### What Happened

I installed and enabled the Blockcode plugin from the asset library into my assets folder under "res" in file manager. I can see the Blockcode files and the icon to enter blockcode mode, but i cannot add a blockcode node, as it does not exist in my nodes directory, and do not see the blocks with which to code. please advise. I really love the feature and would like to use it to create in godot, but as of now, I cannot use it. 

### How to Reproduce

n/a

### Operating System

windows 11

### Anything else?

I installed from the asset library while in a project, enabled it, then restarted. I also did all of the same with a download from github with the same result.

**Comment by dsd** [comment]
Can you share a video of what you're trying here, and confirm the versions of Godot and the block code plugin?
Did you enable the plugin in Project → Project Settings → Plugins?

**Comment by dsd** [comment]
https://www.youtube.com/watch?v=WlUN7Zz0Djg&lc=UgxjEmF3fNMaGSrESwN4AaABAg.A5aYUFJcxg0A5ck-svX-Az
Seems like this was fixed by installing the addon in the right place

**Comment by KingofNothing07** [comment]
I had to remove the main file from the master file and install.
