### ISSUE TITLE
Scrolling and Panning in the code editor

### ISSUE THREAD

**Issue by CaptchaBomb** [endlessm/godot-block-coding#133]
### What Happened

When trying to make complicated block setups such as if <input> or <input> detected then do <action>, often times code blocks will exit the frame of the code editor.

While closing the block lists may widen up the space to code a small bit, implementing a scrolling and panning feature as seen in Scratch or other equivalent block programming tools would be much more helpful in the long run and I believe should be looked at very soon.

### How to Reproduce

N/A

**Comment by manuq** [comment]
@CaptchaBomb thanks! This was already implemented a week ago https://github.com/endlessm/godot-block-coding/pull/120, we just need to release.

**Comment by manuq** [comment]
Zoom and pan has been released: https://github.com/endlessm/godot-block-coding/releases/tag/v0.6.0
