### ISSUE TITLE
Any localization of each text on the blocks? 

### ISSUE THREAD

**Issue by JustusPan** [endlessm/godot-block-coding#146]
### What Happened

How could I help to add a Chinese version for this tool?

### How to Reproduce

none

**Comment by manuq** [comment]
@JustusPan  thank you for the interest! We are under some architectural changes. After that is done, we'll be glad to receive localization contributions in any language. Let's leave these tickets open so we don't forget. I will let you know!

**Comment by wjt** [comment]
Hi @JustusPan  – it is now possible to translate the block coding plugin, though the translations will not be shown until Godot 4.4 due to limitations of 4.3 and older. See the README file for details.
