### ISSUE TITLE
Blocks double themselves everytime i Pick them in godot 4.2.stable release

### ISSUE THREAD

**Issue by AmanVerma0047** [endlessm/godot-block-coding#148]
### What Happened

When I was grabbing the block they double themselves and create this issue , 
<img width="960" alt="Capture" src="https://github.com/user-attachments/assets/f83b6f4d-31e3-4e46-899c-6a6398f300a7">
some blocks broke themselves
![image](https://github.com/user-attachments/assets/3a46d256-694e-49bf-b7db-c6b55ae34337)

### How to Reproduce

1. Add a block code node in characterbody2d.
2. then drag them
3. you will get this issue , I think this can be a version issue i am using godot 4.2 stable version

### Operating System

windows 10 

### Anything else?

Seems Like this issue is happening in godot 4.2 stable release i didnt tested it on other versions.

**Comment by manuq** [comment]
@AmanVerma0047 thanks for reporting! Do you see anything in the Output dock when this happens? If so can you paste the logs here?

**Comment by AmanVerma0047** [comment]
> @AmanVerma0047 thanks for reporting! Do you see anything in the Output dock when this happens? If so can you paste the logs here?

Nope there is no output logs here the plugin thinks that he is working fine so it produce no logs

**Comment by manuq** [comment]
This wasn't reported by anyone else. @AmanVerma0047 please check with the latest version of the plugin and reopen if you can still reproduce the bug. Thanks!

**Comment by AmanVerma0047** [comment]
I can try
