### ISSUE TITLE
O instalar nao funciona 

### ISSUE THREAD

**Issue by mar1br1ght** [endlessm/godot-block-coding#151]
### What Happened

Eu clico em instalar e o pluging não instala

### How to Reproduce

[godot-block-coding-1c877c7589ad35d11a57048b3a2a089039c55332.zip](https://github.com/user-attachments/files/16326123/godot-block-coding-1c877c7589ad35d11a57048b3a2a089039c55332.zip)

### Operating System

Android

**Comment by manuq** [comment]
@mar1br1ght obrigado por informar! Deve ser corrigido pelo #154

**Comment by manuq** [comment]
This should be fixed in latest release https://github.com/endlessm/godot-block-coding/releases/tag/v0.6.1
