### ISSUE TITLE
Add place for Russian localisation

### ISSUE THREAD

**Issue by Lyumih** [endlessm/godot-block-coding#152]
### What Happened

Greetings!
I found a video about your plugin in one of the Godot groups. I really liked it.

There is a proposal to add a place for localizing blocks (Russian and other languages).
This ticket is linked to https://github.com/endlessm/godot-block-coding/issues/146.

The community, or myself in particular, could help with the translation if such an opportunity arises.

Thank you!

### How to Reproduce

none

**Comment by manuq** [comment]
@Lyumih thank you for the interest! We are under some architectural changes. After that is done, we'll be glad to receive localization contributions in any language. Let's leave these tickets open so we don't forget. I will let you know!

**Comment by wjt** [comment]
Hi @Lyumih – it is now possible to translate the block coding plugin, though the translations will not be shown until Godot 4.4 due to limitations of 4.3 and older. See the README file for details.
