### ISSUE TITLE
Sound: Allow dragging and dropping the audio file from the Filesystem dock ($200 bounty)

### ISSUE THREAD

**Issue by cassidyjames** [endlessm/godot-block-coding#166]
### What Happened

I was following along with our own [Block Coding pong tutorial on YouTube around 2:54](https://youtu.be/WlUN7Zz0Djg?si=kic2i7PvVBJ9MCDf&t=174), ~and tried to replicate~ _apparently hallucinated_ Will's action of dragging and dropping a file onto the path. It didn't work, so I had to right-click and copy the path.

I feel like drag and drop is going to be extra important to our target demographic here.

### How to Reproduce

1. Add a "Load file" block to the canvas
2. Try to drag an audio resource to the path

### Block Coding Plugin Version

v0.6.1

### Godot Engine Version

v4.2.2.stable.flathub [15073afe3]

### Operating System

Fedora Silverblue 40

**Comment by manuq** [comment]
@cassidyjames from the video it seems that @wnbaum is also copy/pasting the path, not doing drag and drop.

Besides, I wonder if this should be easier. Eg. all `ogg` files in the project could be blocks that can be dragged directly from the Picker (the blocks palette).

**Comment by manuq** [comment]
The easiest implementation would be:
- Allow dragging files from the Filesystem dock to the Block Coding canvas
- When dropped, a value block is created of type String and value `res://..../` (the resource path)
- Then this block can be attached to the 1st slot of the current "load file () as sound ()".

A much better implementation but also a more complex one:
- Allow dragging sound files from the Filesystem dock to the Block Coding canvas.
- When dropped, the sound is preloaded at the top of the generated script using the resource path. An AudioStreamPlayer is instantiated automatically in the `_ready()` method using that resource. And a value block is created of type String to reference the AudioStreamPlayer instance by name. The name can be the last part of the path using [`String.get_file()`](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-get-file).
- The "play the sound (name)" and "stop the sound (name)" blocks would accept that block, but now the "load file () as sound (name)" block is not needed anymore.

**Comment by dsd** [comment]
Our partner org Endless Studios is offering a modest bounty for completion of this task
(mostly thinking of the easy implementation mentioned above - that could be a good starting point even if we later do the more complex one)
/bounty $40

**Comment by manuq** [comment]
> looks like the easy version of this has been already been solved with #305

Yep, closing this issue then.
