### ISSUE TITLE
Dragging velocities into comparison block sets wrong drop target

### ISSUE THREAD

**Issue by cassidyjames** [endlessm/godot-block-coding#167]
### What Happened

This seems… wrong! 😅 You can drop linear velocity _only_ into the comparison dropdown in the middle (which seems like it shouldn't be a drop target), while you can drop angular velocity into either int spot in addition to the comparison dropdown spot.

[Screencast from 2024-07-26 15-25-59.webm](https://github.com/user-attachments/assets/4120bf06-1975-4dd2-b708-ce649948e6d5)

### How to Reproduce

1. Put a logic comparison block on the canvas
2. Try to drop a linear velocity block into one of the int slots
3. Try to drop the angular velocity block into one of the int slots

### Block Coding Plugin Version

v0.6.1

### Godot Engine Version

v4.2.2.stable.flathub [15073afe3]

### Operating System

Fedora Silverblue 40

### Anything else?

Shout out to the built-in GNOME Shell screen recorder for making this pretty easy to record. :)

**Comment by manuq** [comment]
@cassidyjames thanks! 2 things are happening here:

1. the comparison in the middle should not support dropping anything on it
2. the IF conditional is currently inflexible, it only supports integer values. The angular velocity is an integer (or a float that can be converted to an integer). But the linear velocity is a Vector2 value.
