### ISSUE TITLE
Code blocks disappearing on tab changed, they also won’t save..

### ISSUE THREAD

**Issue by Dracotyoshi** [endlessm/godot-block-coding#168]
### What Happened

The video showcases the issue

https://github.com/user-attachments/assets/557c2eab-64b1-42d4-804e-7df7a611283b

### How to Reproduce

Watch the video 

### Block Coding Plugin Version

Latest 

### Godot Engine Version

Latest 

### Operating System

Windows10

### Logs or command-line output

```shell
No logs
```

**Comment by manuq** [comment]
@Dracotyoshi thank you for the bug report! At least the parse error you mention in the video was fixed by https://github.com/endlessm/godot-block-coding/pull/160 and will be released soon.

**Comment by manuq** [comment]
@Dracotyoshi the fix was released yesterday. Please reopen the issue if you see it again.
