### ISSUE TITLE
Block: "random" math block

### ISSUE THREAD

**Issue by cassidyjames** [endlessm/godot-block-coding#185]
### What Happened

It would be neat to have a "random" block that lets you set a min/max number to use anywhere a value is accepted, e.g. in the pitch entry of a sound block.

### How to Reproduce

N/A

### Block Coding Plugin Version

v0.6.1

### Godot Engine Version

v4.2.2.stable.flathub [15073afe3]

### Operating System

Endless OS 6

**Comment by manuq** [comment]
Addressed by @jfcharron in #194. Will be present in next release.
