### ISSUE TITLE
It is possible to get lost in the editor when changing the zoom level

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/godot-block-coding#186]
### What Happened

When using the block coding editor, it is possible to get lost, particularly when zooming as well as panning. If I find myself looking at a blank canvas, it is unclear what direction to pan in order to find my blocks again.

### How to Reproduce

When using the pong_game example, use the mouse wheel zoom out a long way, then zoom in on an empty space.

### Block Coding Plugin Version

v0.6.2

### Godot Engine Version

v4.2.2.stable

**Comment by manuq** [comment]
Fixed by the PR above. Will be in next release.
