### ISSUE TITLE
not scratchy enough

### ISSUE THREAD

**Issue by lunixgamez** [endlessm/godot-block-coding#189]
### What Happened

please make it a little closer to scratch block wise please there are things that i can do in scratch that i cant do in this block code which annoys me i recommend adding more scratch like features into this extension because so far it is far behind scratch and scratch feels better than this but ill wait because this is early

### How to Reproduce

nb

**Comment by manuq** [comment]
@lunixgamez we are trying to make it better, yes. I will close this issue because it's too generic. If you have a specific suggestion please open a new one.
