### ISSUE TITLE
Add Chinese localization files

### ISSUE THREAD

**Issue by DeepChTi** [endlessm/godot-block-coding#200]
### What Happened

Where is the localized language file, I want to help this tool add Chinese language

### How to Reproduce

not

### Block Coding Plugin Version

v0.6.2

### Logs or command-line output

```shell
not
```

### Anything else?

not

**Comment by manuq** [comment]
Thank you @DeepChTi, see also #146.

**Comment by wjt** [comment]
Hi @DeepChTi  – it is now possible to translate the block coding plugin, though the translations will not be shown until Godot 4.4 due to limitations of 4.3 and older. See the README file for details.

**Comment by DeepChTi** [comment]
> Hi @DeepChTi – it is now possible to translate the block coding plugin, though the translations will not be shown until Godot 4.4 due to limitations of 4.3 and older. See the README file for details.

ok

**Comment by wjt** [comment]
Hi, @DeepChTi, I saw your request on Transifex to add Chinese (zh). I've declined it because (quoting @dbnicholson from elsewhere):

> As it turns out, zh is equivalent to zh_CN in Godot. See https://github.com/godotengine/godot-proposals/issues/11119 for details. A generic zh translation would never be used, which is why Godot doesn't provide one for the editor, either.
