### ISSUE TITLE
add duplicate function for easy use ($200 bounty)

### ISSUE THREAD

**Issue by FakeDivinity** [endlessm/godot-block-coding#201]
### What Happened

its a waste of time for doing duplication it manually

### How to Reproduce

add a function where i can haver the existing code block and duplicate it when release

### Block Coding Plugin Version

0.6.2

### Godot Engine Version

4.3

### Operating System

windows11

**Comment by manuq** [comment]
Yes! This would be a great contribution.

**Comment by manuq** [comment]
For someone wanting to implement this, here is a proposal:
- Display a dropdown menu when the user right-clicks on a block.
- Add options: Duplicate and Delete to the dropdown menu.
- Add shortcut Ctrl-D to Duplicate.

The Delete functionality is already there, but only available from the Del shortcut.

**Comment by dsd** [comment]
Our partner org Endless Studios is offering a modest bounty for completion of this task
/bounty $50

**Comment by manuq** [comment]
There is a PR that adds the duplicate functionality among other things https://github.com/endlessm/godot-block-coding/pull/293

I think that the other things should be discussed first. The duplicate is definitely wanted, so if they can be split into a separate PR (or the other stuff removed) I'll give a review.

**Comment by Gyan-max** [comment]
Is this still available to be resolved? 
please let me know, if I can get assigned

**Comment by manuq** [comment]
@dsd please award @urbit-pilled .
