### ISSUE TITLE
Make text for yellow blocks black or change yellow to something darker

### ISSUE THREAD

**Issue by wareya** [endlessm/godot-block-coding#202]
### What Happened

The yellow blocks are really hard to read, especially on displays with poor contrast, overly bright gamma settings, or glare.

### How to Reproduce

Add a yellow block and see it being hard to read the label.

### Anything else?

Adding a black outline or dropshadow, or making the text black with a white outline or dropshadow, might also help instead. Lots of options. It's just really hard to read text-background color combinations that have poor contrast.

**Comment by manuq** [comment]
@wareya can you share a screen capture? You are probably trying an old release. Or maybe the last release has the blocks for Pong with old colors. This won't be the case anymore in next release because now the colors are not persisted in the project anymore.

**Comment by wareya** [comment]
Oh, the yellow nodes are gone and it's only the light orange ones now. The light orange is a lot better than the yellow, but it's still hard to read.

![image](https://github.com/user-attachments/assets/347b8ab8-9672-46dd-8ce7-a82796b40792)

Here's what it might look like on a monitor with bright gamma:

![image](https://github.com/user-attachments/assets/8e02dc50-92cd-43e8-91eb-f9ea66a5759e)

**Comment by manuq** [comment]
@wareya would you like to provide an alternative color code? I borrowed this one from the CSS of Microsoft MakeCode Arcade, but their font is bold so it looks better:
![Captura desde 2024-08-22 16-40-43](https://github.com/user-attachments/assets/dbe639b8-4f69-4e01-860b-0673409b0ff7)

**Comment by wareya** [comment]
`e06000` seems to have enough contrast (bottom node):

![image](https://github.com/user-attachments/assets/b379702e-bb07-4646-a688-ac4821ac8f26)

It's starting to get into brown territory, but I think that's better than being hard to read.

I feel like doing a second pass over the colors might be a good idea in general; the light and dark green/blue look *very* similar to their counterparts in terms of brightness, and the magenta of "sounds" doesn't fit in with the other, more muted colors. Also the red-orange of "input" might look better with a little less orange and a little more black.

**Comment by manuq** [comment]
> I feel like doing a second pass over the colors might be a good idea in general; the light and dark green/blue look _very_ similar to their counterparts in terms of brightness, and the magenta of "sounds" doesn't fit in with the other, more muted colors. Also the red-orange of "input" might look better with a little less orange and a little more black.

@wareya yes please! If you would like to give a pass over all the colors, here is where they are defined:  https://github.com/endlessm/godot-block-coding/blob/aa80f0cbd30616268a1cdb86fe3e65152434a3f8/addons/block_code/ui/constants.gd#L18

**Comment by manuq** [comment]
@wareya for now I have merged your color suggestion to fix the readability as in https://github.com/endlessm/godot-block-coding/issues/202#issuecomment-2305525509 . Would you still like to give a pass through all the colors?

**Comment by wareya** [comment]
Currently very busy... I'll try to make the time for it, but no promises!
