### ISSUE TITLE
Theme block dropdowns 

### ISSUE THREAD

**Issue by manuq** [endlessm/godot-block-coding#203]
### What Happened

The dropdowns look wrong, especially for the Light theme.

### How to Reproduce

1. Change Godot to Light theme in Editor Settings
2. Open the Pong example, click Block Code for a paddle
3. See the dropdowns in the "Move with player..." block:
![Captura desde 2024-08-22 16-24-13](https://github.com/user-attachments/assets/2a9afbfb-d8fe-497a-b835-0f9260934bb4)

### Block Coding Plugin Version

main

### Godot Engine Version

v4.3

### Operating System

Endless OS

**Comment by DoomTas3r** [comment]
Is this good?

https://github.com/endlessm/godot-block-coding/pull/245#issue-2567611164
