### ISSUE TITLE
No BlockCode child node

### ISSUE THREAD

**Issue by Retro7Development** [endlessm/godot-block-coding#208]
### What Happened

There is no BlockCode node, please add it :)

### How to Reproduce

1. Try to add BlockCode node
2. Fail to add BlockCode node

**Comment by maeonian** [comment]
Experiencing the same issue. Latest version of Blocks via AssetLib, using Godot 4.3.

**Comment by manuq** [comment]
Can you provide which operating system? Can you provide a screen capture of you trying to add the node using the "+" icon in the Screen Tree dock and then searching for "block"? I am not able to reproduce this:
![Captura desde 2024-09-05 10-31-06](https://github.com/user-attachments/assets/4d8e0a1b-e531-482e-8538-ca0b124d398c)

**Comment by maeonian** [comment]
I'm not OP but I'm on Windows 11, Godot 4.3. On a completely new Godot project, added Blocks via AssetLib. 
<img width="458" alt="image" src="https://github.com/user-attachments/assets/26f76b42-0fd8-470a-ae59-92dc6513acdb">

**Comment by manuq** [comment]
OK! It was a matter of enabling the plugin then. Yeah I find that a bit tricky too, hopefully the plugins get enabled automatically in Godot soon, removing that extra step.
