### ISSUE TITLE
SimpleCharacter texture can dissapear while editing

### ISSUE THREAD

**Issue by manuq** [endlessm/godot-block-coding#213]
### What Happened

If I switch to another scene, the texture dissapears from the editor:
[Grabación de pantalla desde 2024-09-05 10-14-19.webm](https://github.com/user-attachments/assets/c0c705bf-7a53-4c14-8d44-97a1b22adfe3)

Trying to set the texture again shows an error in the Output panel (see below).

By the way in the game it looks fine.

### How to Reproduce

1. Add a SimpleCharacter node
2. Add a texture to it
3. Switch to another scene, then back

### Block Coding Plugin Version

main

### Godot Engine Version

v4.3

### Operating System

Endless OS

### Logs or command-line output

```shell
res://addons/block_code/simple_nodes/simple_character/simple_character.gd:47 - Invalid assignment of property or key 'texture' with value of type 'CompressedTexture2D' on a base object of type 'Nil'.
```

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
