### ISSUE TITLE
how ican use velocity.x it self 

### ISSUE THREAD

**Issue by wesamdev** [endlessm/godot-block-coding#248]
### What Happened

i cant make player movement with jump correctly because i cant set velocity.x it self without set y to 0****

### How to Reproduce

go to velocity tab and add set velocity

### Block Coding Plugin Version

v0.7.1 Latest

### Godot Engine Version

v4.4.0-dev redot

### Operating System

windows 10 pro x64

**Comment by dylanmccall** [comment]
Fixed in 877f5625f29c4e6210ade9afd4194a1ba3abd36e.

**Comment by dylanmccall** [comment]
Thank you for your suggestion! :)

**Comment by wesamdev** [comment]
thanks for the fix

**Comment by wesamdev** [comment]
> Thank you for your suggestion! :)

please add it also for velocity
