### ISSUE TITLE
add physics process

### ISSUE THREAD

**Issue by wesamdev** [endlessm/godot-block-coding#261]
### What Happened

please add physics process loop

### How to Reproduce

nothing

### Block Coding Plugin Version

v0.7.1 Latest

### Godot Engine Version

v4.4.0-dev redot

### Operating System

windows 10 pro x64

**Comment by manuq** [comment]
Thanks. We had this before and it was intentionally removed, because it is a bit confusing for learners to have two different main loops. And because for the default Godot project, the physics loop and the screen refresh loop run at the same pace.

**Comment by manuq** [comment]
Here is a proposal to make this happen: #282

**Comment by manuq** [comment]
Thanks for your contribution, @DoomTas3r .
