### ISSUE TITLE
When will support for 4.3 come?

### ISSUE THREAD

**Issue by CoderGuyTedd** [endlessm/godot-block-coding#266]
### What Happened

I wanted to know when the support for godot 4.3 is plannedGodot

### How to Reproduce

Not a issue but a question

### Godot Engine Version

4.3!!!!

**Comment by manuq** [comment]
Hi @CoderGuyTedd . The block coding plug-in works in Godot v4.3 as you can see in the project.godot file. It works in 4.2 too. But I wonder what makes you think otherwise? Is there a document or a reference that got outdated? Thanks.

**Comment by CoderGuyTedd** [comment]
its not on the assetlib for godot 4.3

**Comment by manuq** [comment]
> its not on the assetlib for godot 4.3

I opened Godot 4.3, went to the Assetlib tab, then I searched for "block coding". And there it is:
 
![Captura desde 2024-10-17 13-45-01](https://github.com/user-attachments/assets/333c32ee-d017-426b-ad9a-ba0034e3d254)
