### ISSUE TITLE
expose variable type on hover

### ISSUE THREAD

**Issue by cassidyjames** [endlessm/godot-block-coding#271]
### What Happened

We fought with what we thought was a bug but we were trying to snap a string into a float spot

### How to Reproduce

1. Create a string variable
2. Create a comparison block
3. Try to drag the string into the comparison, forgetting it's a string
4. Be sad

**Comment by DoomTas3r** [comment]
I thought it would be like the preview block. The extra backgroud shape variants can also be used to express different types

**Comment by cassidyjames** [comment]
Having it on hover is better than not having it at all. 😉 But yeah, something more visual could be helpful. I like the idea of distinct shapes for distinct types, but we'd want to make sure that's consistent across all the blocks.

I do still think being explicit with a tooltip (in addition to anything visual) would be beneficial and in line with our design of natural language plus helpful/technical tooltips elsewhere, though. Ultimately we're designing primarily for laptop/desktop users for our learning programs.

Maybe we add a tooltip as a first pass, and then do a more thorough follow-up with distinct shapes across all block types?

**Comment by manuq** [comment]
@cassidyjames @DoomTas3r sounds good. We already have a tooltip, so it's a matter of adding a new line with the type. For example, for a Node2D under "Transform | Position", the "position" value block should say:

> The position property
>
> Type: Vector2

Long term, we have considered different shapes in the past, but there are so many that it will become a bit weird. I think an icon would be better.

Also at one point we would like to separate Vector2 in the 2 components, so there is one less type.
