### ISSUE TITLE
Make the block coding system work in game, not just in the editor

### ISSUE THREAD

**Issue by goatchurchprime** [endlessm/godot-block-coding#274]
### What Happened

There are uses for this drag-and-drop coding system within a running game system to give it a kind of extreme configurability.  For example, a [runtime version of this module](https://github.com/DanielSnd/runtime_godot_block_coding) this module was made for the Heroes card game two stands down from the Endless stand at Godotcon2024.

An in-game version of Block Coding would also provide the capability to run this feature under Godot's multiplayer system for the purpose of remote collaboration/coaching/teaching, since the editor itself is unlikely ever to be upgraded to multiplayer.

### How to Reproduce

When I instantiate res://addons/block_code/ui/main_panel.tscn into a game it doesn't work due to numerous references to `EditorInterface.get_inspector()`, a single global instance of `BlockEditorContext`, and so forth.

### Block Coding Plugin Version

v0.7

### Godot Engine Version

v4.3

### Operating System

Nixos

**Comment by DoomTas3r** [comment]
Features that rely on the editor (like dragging nodes from the scene tree) would have to be removed to enter it in a game environment. Instead, why not a multiplayer version of this plugin with a pull request? I haven't made any multiplayer games yet, but it seems that a multiplayer plugin should be possible

**Comment by goatchurchprime** [comment]
Duplicate of https://github.com/endlessm/godot-block-coding/issues/196
