### ISSUE TITLE
Add "Advanced" blocks filter ($200 bounty)

### ISSUE THREAD

**Issue by manuq** [endlessm/godot-block-coding#282]
### What Happened

Being a learning tool, the available blocks are constrained by default. Still, it would be nice to have more advanced blocks for advanced learners.

When [we switched from technical language](https://github.com/endlessm/godot-block-coding/commit/79d871bb65dcceef8557111ad551f903c52cfe24) (like "on ready" / "on process") to natural language (like "when starting" / "every frame") we dropped the "on physics process" block. Because it was confusing to have two game loops and because the default Godot runs `_process` and `_physics_process` at the same pace. But advanced learners can benefit from such block as proposed in #261 .

Proposal:
- Add an `is_advanced` export boolean property to the BlockDefinition. False by default.
- Add an "Advanced" checkbox to the dock title to unfilter advanced blocks. It should be turned off by default. When checked, advanced blocks are listed in the block palette (aka "block picker")

### How to Reproduce

N/A, this is a proposal.

**Comment by dsd** [comment]
Our partner org Endless Studios is offering a modest bounty for completion of this task
/bounty $30

**Comment by manuq** [comment]
@dsd let's make sure that @urbit-pilled is awarded, as the PR was just merged.
