### ISSUE TITLE
Collapse/expand blocks for "advanced" settings ($200 bounty)

### ISSUE THREAD

**Issue by manuq** [endlessm/godot-block-coding#288]
### What Happened

As we improve the blocks, more settings are being appended to them. These are usually left with the defaults and intended for advanced usage. For example:
![Captura desde 2024-10-23 13-40-44](https://github.com/user-attachments/assets/5f1e2ab2-840e-4fbe-8693-96e65103ffa3)

Proposal: allow blocks to expand/collapse to hide the advanced settings. Blocks should be collapsed by default.

Here is how Microsoft MakeCode Arcade does it:
![Captura desde 2024-10-23 13-32-43](https://github.com/user-attachments/assets/6da88c4d-9ef8-48f4-b310-c14b4d0cd1c6)
![Captura desde 2024-10-23 13-32-57](https://github.com/user-attachments/assets/046935fc-3432-4fd1-9488-f142552a6668)

Implementation: there should be a (+) button at the end of collapsed blocks, and a (-) button at the end of expanded blocks. The format of the block label template should be enhaced to define where the cut should happen. Maybe with a `|` character? So the label template of the sound block above would look like:
```
play the sound {name: STRING} | with volume {db: FLOAT} dB and pitch scale {pitch: FLOAT}
```
Pay attention to the `|` that is separating how it should look collapsed `play the sound {name: STRING}` and the advanced stuff (volume and pitch scale settings).

### How to Reproduce

N/A this is a feature proposal.

**Comment by wjt** [comment]
Another example of a block that this might be useful on is the “every frame" block. In some cases it would be useful to expose the `delta` parameter.

- https://github.com/endlessm/godot-block-coding/pull/255

**Comment by dsd** [comment]
Our partner org Endless Studios is offering a modest bounty for completion of this task
/bounty $40

**Comment by dsd** [comment]
Our partner org Endless Studios is offering a modest bounty for completion of this task
/bounty $200

**Comment by dsd** [comment]
Our partner org Endless Studios is offering a modest bounty for completion of this task
/bounty $200

**Comment by joaquin30** [comment]
/attemp #288

I will modify the parsing of display templates in addons/block_code/code_generation/block_definition.gd and addons/block_code/ui/blocks/utilities/template_editor/template_editor.gd, and add a new control node for collapse/expand options.

**Comment by joaquin30** [comment]
Hi, I have a prototype that uses an HBoxContainer to expand/collapse options. The icons were made by me in Libresprite, and the size and shape can change. Also, I assume that the "play sound" block is not the only one that should be collapsed, what other blocks should I change?

**Comment by manuq** [comment]
> Hi, I have a prototype that uses an HBoxContainer to expand/collapse options. The icons were made by me in Libresprite, and the size and shape can change. Also, I assume that the "play sound" block is not the only one that should be collapsed, what other blocks should I change?

The prototype is working! I think you can also split between basic/advanced in `animationplayer_play`:
`"play {animation: STRING} | {direction: NIL} {wait_mode: 
NIL}"`

Please mark it as ready for review when you think it's done.

**Comment by joaquin30** [comment]
I'm modifying the icons for a better look, but one thing I notice is that I can't see the `animationplayer_play` block in my fork and in the main branch. @manuq can you tell me where is this is normal? Also I have notice some cleanup errors when running the tests:

```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2284)
Leaked instance: GDScriptNativeClass:9223372056719000566
Leaked instance: GDScript:9223372099316352925 - Resource path: res://addons/block_code/serialization/block_serializatiod
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not free.
ERROR: 1 resources still in use at exit.
   at: clear (core/io/resource.cpp:599)
Resource still in use: res://addons/block_code/serialization/block_serialization.gd (GDScript)
```

**Comment by manuq** [comment]
> I'm modifying the icons for a better look, but one thing I notice is that I can't see the `animationplayer_play` block in my fork and in the main branch. @manuq can you tell me where is this is normal? Also I have notice some cleanup errors when running the tests:

It is this file: [addons/block_code/blocks/graphics/animationplayer_play.tres](https://github.com/endlessm/godot-block-coding/blob/main/addons/block_code/blocks/graphics/animationplayer_play.tres)

But you will only see the block in the selector if you attach a Block Code node to an AnimationPlayer node.

And yes, I agree that the icons look pixelated. Please use SVG files.

> 
> ```
> WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
>      at: cleanup (core/object/object.cpp:2284)
> Leaked instance: GDScriptNativeClass:9223372056719000566
> Leaked instance: GDScript:9223372099316352925 - Resource path: res://addons/block_code/serialization/block_serializatiod
> Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not free.
> ERROR: 1 resources still in use at exit.
>    at: clear (core/io/resource.cpp:599)
> Resource still in use: res://addons/block_code/serialization/block_serialization.gd (GDScript)
> ```

The GUT tests run fine in your branch. No errors or warnings here! In Godot 4.3 stable.

I'm reopening the issue for the remaining things:
- Better icon
- animationplayer_play advanced settings

**Comment by manuq** [comment]
@joaquin30 thanks for your contribution!

@dsd please award this contributor.
