### ISSUE TITLE
{Feature] Would you add the ability to make globally available variables and functions?

### ISSUE THREAD

**Issue by 111ukasz111** [endlessm/godot-block-coding#310]
### What Happened

I don't need to explain it.

### How to Reproduce

I don't need to explain it.

### Block Coding Plugin Version

0.7.1

### Godot Engine Version

4.3

### Operating System

Windows10

**Comment by manuq** [comment]
@111ukasz111 sorry but yes, you will need to explain a bit. Variables can already be defined under "Variables" in the blocks palette. Functions can be defined under "Communication | Methods" in the block palette, with the block "define method {method name}".

**Comment by manuq** [comment]
No more feedback from the reporter, so closing.
