### ISSUE TITLE
{Feature] Could you add these blocks from the "scratch" programing language please?

### ISSUE THREAD

**Issue by 111ukasz111** [endlessm/godot-block-coding#314]
### What Happened

Those blocks are: "Move 10 steps", "Own block" (with ability to create your own arguments), "Set Rotation style"

### How to Reproduce

=

### Block Coding Plugin Version

0.7.1

### Godot Engine Version

4.3

### Operating System

Windows10

**Comment by flybot2010-lab** [comment]
Equivalent Blocks Are Already Available When Using Applicable Nodes.

**Comment by manuq** [comment]
@111ukasz111 what would be a step in Godot?

Scratch and Godot are very different, so what you ask is not possible, sorry. Please read how this is a layer on top of Godot and how we embrace Godot concepts in our [pedagogy document](https://github.com/endlessm/godot-block-coding/blob/main/docs/PEDAGOGY.md#a-layer-on-top-of-godot).

With that said, a high level abstraction "Simple" node could be contributed to draw while moving and rotating like in [Logo Turtle](https://en.wikipedia.org/wiki/Turtle_(robot)). If that's close to what you are asking. That will have to be implemented.
